#fist workflow
name: Firmware CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master  
jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: download code
        uses: actions/checkout@v3
      - name: buld docker image
        run: docker build -t embedded-tooclhain:v1 .
      - name: build firmware
        run: docker-compose run --rm build
      - name: Run static analysis
        run: docker-compose run --rm analyze
      - name: clean build artifacts
        run: docker-compose run --rm clean
